name: android-test

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build-test:
    if: github.event.pull_request.draft == false
    runs-on: [ self-hosted, macOS, ARM64 ]
    strategy:
      matrix:
        api-level: [ 34 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env

      - name: Build tests
        working-directory: android
        run: ./gradlew app:assembleAndroidTest

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          avd-name: ci-actions-avd
          target: google_apis
          arch: arm64-v8a
          ndk: 25.1.8937393
          cmake: 3.18.1
          script: cd android; ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.notClass=com.xrpllabs.xumm.DetoxTest --info

      - name: Test Summary
        uses: test-summary/action@dist
        with:
          paths: android/app/build/outputs/androidTest-results/connected/**/*.xml
          show: "all"
        if: always()

