name: e2e

on: [pull_request]

jobs:
  build-run:
    if: "contains(github.event.commits[0].message, '[include e2e]')"
    runs-on: macos-11

    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - run: node --version

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: npx detox clean-framework-cache && npx detox build-framework-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..
      - name: Prepare
        run: |
          brew tap wix/brew
          brew install applesimutils
          make build-env
          make generate-locales
          mv src/app.tsx src/app.tsx.old && cat src/app.tsx.old|perl -pe'BEGIN{undef $/;} s/if \(isJailBroken.+?}/\/\/ No root or jailbreak detection/gms' > src/app.tsx

      - run: npx detox build e2e --configuration ios.sim.release
      - run: npx cucumber-js ./e2e --configuration ios.sim.release

      - name: Upload artifact files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: e2e/artifacts/
