name: test

on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Yarn 3
        run: npm install -g yarn@3.5.1

      - run: node --version

      - name: Cache node_modules/
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-
      - run: yarn install --immutable --frozen-lockfile

      - run: yarn test
        env:
          CI: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
