name: validate

on: [pull_request]

jobs:
  validate-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - run: node --version

      - name: Cache node_modules/
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - run: npm ci

      - run: npm run validate
        if: ${{ always() }}
