name: validate
env:
  CI: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: [ self-hosted, macOS, ARM64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env

      - run: npm run validate
        if: ${{ always() }}
